@startuml
'https://plantuml.com/sequence-diagram
title Un Auto Atraviesa La Ciudad Y Se Encuentra Con Un Piquete No Pasa
autonumber
actor ":TestCase"
Activate ":TestCase"
":TestCase" -> ":Vehiculo": moverseHacia (unaDireccion)
Activate ":Vehiculo"
create ":MovimientoComun"
":Vehiculo" -> ":MovimientoComun": <<new Movimiento (unaDireccion) >>
Activate ":MovimientoComun"
":Vehiculo" -> ":MovimientoComun": mover (unaCalle, :Vehiculo)
":MovimientoComun" -> ":CalleComun": serTransitada (:Vehiculo)
Activate ":CalleComun"
":CalleComun" -> ":Vehiculo": afectarMovimientos (unPozo:Obstaculo)
":Vehiculo" -> "unPozo:Obstaculo": calcularPenalizacion (unAuto:TipoDeVehiculo)
Activate "unPozo:Obstaculo"
"unPozo:Obstaculo" -> "unAuto:TipoDeVehiculo": calcularPenalizacion (unPozo:Obstaculo)
Activate "unAuto:TipoDeVehiculo"
return VehiculoNoPuedePasar
return VehiculoNoPuedePasar
":TestCase" <--":Vehiculo": VehiculoNoPuedePasar



@enduml