@startuml
title Diagrama General


Vehiculo "1" -d-> "1" TipoDeVehiculo
Vehiculo "1" -d-> "1" Posicion
Vehiculo "1" .r.> "1" MovimientoComun
Vehiculo "1" .r.> "1" Direccion


MovimientoComun "1" .r.> "1" Direccion
MovimientoComun "1" .d.> "1" Grilla

Grilla "1" -d-> "*" Ubicables
Grilla "1" .r.> "1" Vehiculo

TipoDeVehiculo <|-d- Auto
TipoDeVehiculo <|-d- Moto
TipoDeVehiculo <|-d- CuatroPorCuatro

class Vehiculo {}

class MovimientoComun {}

interface Direccion {}

abstract class TipoDeVehiculo {}

interface Ubicables {}

@enduml

Vehiculo"1" ..>  "1" Obstaculo
Calle "1" ..>  "1" Vehiculo
Posicion "1" -> "1..*" Calle
Posicion "1" ..>  "1" Direccion
TipoDeVehiculo"1" ..>  "1" Obstaculo
Juego "1" -> "*" Jugador
Calle "1" -r-> "2" Posicion
Calle "1" o-- "*" Sorpresa
Calle "1" o-- "*" Obstaculo
Vehiculo "1" --> "1" Posicion
Grilla  "1" -> "*" Posicion
Grilla  "1" -> "*" Calle
Juego "1" -> "1" Grilla
Jugador "1" o-- "1" Vehiculo
Vehiculo "1" ..>  "1" Movimiento
Vehiculo "1" ..>  "1" Direccion
Movimiento "1" -> "1"Direccion
Movimiento "1" ..> "1"Calle
Vehiculo "1" *-- "1"TipoDeVehiculo
Sorpresa "1" ..> "1"Vehiculo