@startuml
'https://plantuml.com/class-diagram

Pozo .u.|> Obstaculo
Piquete .u.|>  Obstaculo
ControlPolicial .u.|>  Obstaculo
NoObstaculo .u.|>  Obstaculo

class Pozo {
+ estaEnPosicion(Posicion:): boolean
 + serEncontradoPor(Vehiculo:): void
 + calcularPenalizacion(TipoDeVehiculo:):int
}

class ControlPolicial {
+ estaEnPosicion(Posicion:): boolean
 + serEncontradoPor(Vehiculo:): void
 + calcularPenalizacion(TipoDeVehiculo:):int
}
class Piquete {
+ estaEnPosicion(Posicion:): boolean
 + serEncontradoPor(Vehiculo:): void
 + calcularPenalizacion(TipoDeVehiculo:):int
}
class NoObstaculo {
+ estaEnPosicion(Posicion:): boolean
 + serEncontradoPor(Vehiculo:): void
 + calcularPenalizacion(TipoDeVehiculo:):int
}

interface Obstaculo {
 + {abstract}serEncontradoPor(Vehiculo:): void
}

@enduml