@startuml
title Diagrama De Clase Grilla

MovimientoComun "1" .d.> "1" Grilla
Grilla "1" -d-> "*" Ubicables
Grilla "1" .r.> "1" Vehiculo

class MovimientoComun {
    - int cantidadDeMovimientos;
    + MovimientoComun(Direccion): void
    + moverse (Vehiculo): void
}

class Grilla {
    - unaGrilla: Grilla
    - maximaCantidadDePosicionesEnX: int
    - maximaCantidadDePosicionesEnY: int
    + crearPosiciones(): void
    + aplicarElementoUbicableAVehiculo (Vehiculo) : void
    + agregarUbicable (Ubicables) :  void
}
class Vehiculo {
    - posicion: Posicion
    - unTipoDeVehiculo: TipoDeVehiculo
    - cantidadDeMovimientos: int
    + moverseHacia(Direccion unaDireccion): void
    + aumentarCantidadMovimientosEnPorcentaje(Double porcentaje): void
    + disminuirCantidadMovimientosEnPorcentaje(Double porcentaje): void
    + proximoVehiculo():void
    + cambiarPosicionHacia(Posicion unaPosicion): void
    + ToparseConUn(Ubicable unUbicable): void
}

interface Ubicables {
    + {abstract} estaEnPosicion(Posicion): boolean
    + {abstract} serEncontradoPor(Vehiculo): void
}

@enduml