@startuml
autonumber
actor ":TestCase"

":TestCase" -> "j1:Jugador": moverHacia (unaDireccion)
"j1:Jugador" -> ":Movimiento": moverHacia (unaPosicion, unVehiculo, unaDireccion)
":Movimiento" -> "Calle": esTransitadoPor (unVehiculo)
"Calle" -> ":Obstaculo":  esTransitadoPor(unVehiculo)
":Obstaculo" -> ":Vehiculo":  agregarCantMov(3)
":Obstaculo" -> ":Vehiculo":  nuevaPosicion(proxPosicion)



@enduml