@startuml
@startuml
'https://plantuml.com/sequence-diagram
title Un Vehiculo Atraviesa La Ciudad Y Se Encuentra Con Un Obstaculo
autonumber
actor ":TestCase"
Activate ":TestCase"
   ":TestCase" -> ":Vehiculo": moverseHacia (:Direccion)
    Activate ":Vehiculo"
    create ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": << new Movimiento >>
    ":Vehiculo" -> ":MovimientoComun": mover (:CalleComun, :Vehiculo)

    Activate ":MovimientoComun"
    ":MovimientoComun" -> ":CalleComun": esTransitada (:Vehiculo)

    Activate ":CalleComun"
    ":CalleComun" -> ":Obstaculo": esAtravesadoPor (:Vehiculo)

    Activate ":Obstaculo"
    ":Obstaculo" -> ":TipoDeVehiculo": seEncuentraUnObstaculo()

    Activate ":TipoDeVehiculo"
    return movimientos
    return movimientos
    return movimientos
    ":MovimientoComun" -> ":MovimientoComun": cambiarPosicion()
    return movimientos
    Deactivate ":TipoDeVehiculo"
    Deactivate ":Obstaculo"
    Deactivate ":CalleComun"
    Deactivate ":MovimientoComun"


    ":TestCase"  -> ":Vehiculo": getCantidadDeMovimientos ()
    ":TestCase"  <-- ":Vehiculo": cantidadDeMovimientos
    Deactivate ":Vehiculo"


@enduml

@enduml