@startuml
'https://plantuml.com/sequence-diagram
title Una 4x4 Atraviesa 3 Pozos Y Es Penalizada Con 3 Movimientos
autonumber
actor ":TestCase"
Activate ":TestCase"
loop para 3 Pozos
   ":TestCase" -> ":Vehiculo": moverseHacia (unaDireccion)
    Activate ":Vehiculo"
    create ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": <<new Movimiento (unaDireccion) >>
    Activate ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": mover (unaCalle, :Vehiculo)
    ":MovimientoComun" -> ":CalleComun": serTransitada (:Vehiculo)
    Deactivate ":MovimientoComun"
    Activate ":CalleComun"
    ":CalleComun" -> ":Vehiculo": afectarMovimientos (unObstaculo)
    Deactivate ":CalleComun"
end
    ":Vehiculo" -> ":CuatroPorCuatro": calcularPenalizacion (unObstaculo)
    Activate ":CuatroPorCuatro"
    ":Vehiculo" <-- ":CuatroPorCuatro": cantidadDeMovimientos
    Deactivate ":CuatroPorCuatro"
    ":TestCase"  -> ":Vehiculo": getCantidadDeMovimientos ()
    ":TestCase"  <-- ":Vehiculo": cantidadDeMovimientos
    Deactivate ":Vehiculo"


@enduml