@startuml
'https://plantuml.com/sequence-diagram
title Diagrama 4x4 Atraviesa La Ciudad Y Se Encuentra con Sorpresa Cambio De Vehiculo
autonumber
actor ":TestCase"

Activate ":TestCase"
   ":TestCase" -> "unVe:Vehiculo": moverseHacia (unaDireccion)
    Activate "unVe:Vehiculo"
    create ":MovimientoComun"
    "unVe:Vehiculo" -> ":MovimientoComun": <<new Movimiento (unaDireccion) >>
    "unVe:Vehiculo" -> ":MovimientoComun": moverse (unVe)
    Activate ":MovimientoComun"
    ":MovimientoComun" -> "unVe:Vehiculo": cambiarPosicionHacia (:PosicionRelativa)
    ":MovimientoComun" -> ":Grilla": aplicarElementoUbicable(unVe)
    Deactivate ":MovimientoComun"
    Activate ":Grilla"
    loop Por Cada Ubicable de la Lista
    ":Grilla" -> "unVe:Vehiculo": toparseCon(:Ubicable)
    "unVe:Vehiculo" -> ":Ubicable": estaEnPosicion(:Posicion)
    Activate ":Ubicable"
    end


    "unVe:Vehiculo" <- ":Ubicable": proximoVehiculo()
    "unVe:Vehiculo" -> ":4x4": proximoTipoDeVehiculo()
    Activate ":4x4"
    return unaMoto:Moto
    "unVe:Vehiculo" -> "unVe:Vehiculo":tipoDeVehiculo = unaMoto
    Deactivate ":Ubicable"
    Deactivate ":Grilla"
    ":TestCase" -> "unVe:Vehiculo": getTipoDeVehiculo()
    return tipoDeVehiculo

@enduml