@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor ":TestCase"
Activate ":TestCase"
loop paraUnaCantidadDeMovimientosDeterminada
    ":TestCase" -> "j1:Jugador": moverVehiculoHacia (unaDireccion)
    Activate "j1:Jugador"
    "j1:Jugador" -> ":Moto": moverHacia(unaDireccion)
    Activate ":Moto"
    create ":Movimiento"
    ":Moto" -> ":Movimiento": <<new Movimiento (unaDireccion) >>
    Activate ":Movimiento"
    ":Moto" -> ":Movimiento": moverse (esquinaActual, j1:Jugador)
    ":Movimiento" -> ":Calle": serTransitada (j1:Jugador)
    Activate ":Calle"
    ":Calle" -> "j1:Jugador" : modificarCantidadDeMovimientos (X:int)
     "j1:Jugador" -> ":CantidadDeMovimientos" : modificar (X:int)
     ":Movimiento" <-- ":Calle": otraEsquina
     Deactivate ":Calle"
     Deactivate ":Movimiento"
     ":Moto" <-- ":Movimiento": otraEsquina
     Deactivate ":Moto"
     Deactivate "j1:Jugador"
end
":TestCase" -> "j1:Jugador": obtenerCantidadDeMovimientos ()
Activate "j1:Jugador"
"j1:Jugador" -> ":CantidadDeMovimientos": obtenerCantidadDeMovimientos ()
Activate ":CantidadDeMovimientos"
"j1:Jugador" <-- ":CantidadDeMovimientos": X:int
Deactivate ":CantidadDeMovimientos"
":TestCase" <-- "j1:Jugador": X:int
Deactivate "j1:Jugador"



@enduml