@startuml
'https://plantuml.com/sequence-diagram
title Un Auto Atraviesa La Ciudad Y Se Encuentra Con Un Piquete No Puede Pasar
autonumber
actor ":TestCase"
Activate ":TestCase"
   ":TestCase" -> ":Vehiculo": moverseHacia (unaDireccion)
    Activate ":Vehiculo"
    create ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": <<new Movimiento (unaDireccion) >>
    Activate ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": mover (unaCalle, :Vehiculo)
    ":MovimientoComun" -> ":CalleComun": serTransitada (:Vehiculo)
    Deactivate ":MovimientoComun"
    Activate ":CalleComun"
    ":CalleComun" -> ":Vehiculo": afectarMovimientos (unObstaculo)
    Deactivate ":CalleComun"
    ":Vehiculo" -> ":Auto": calcularPenalizacion (unObstaculo)
    Activate ":Auto"
    ":Vehiculo" <-- ":Auto": VehiculoNoPuedePasar Excepcion
    Deactivate ":Auto"
    ":TestCase"  <-- ":Vehiculo": VehiculoNoPuedePasar Excepcion
    Deactivate ":Vehiculo"


@enduml