@startuml
'https://plantuml.com/sequence-diagram
title Un Auto Atraviesa La Ciudad Y Se Encuentra Con Una Sorpresa Favorable
autonumber
actor ":TestCase"
Activate ":TestCase"
   ":TestCase" -> ":Vehiculo": moverseHacia (unaDireccion)
    Activate ":Vehiculo"
    create ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": <<new Movimiento (unaDireccion) >>
    Activate ":MovimientoComun"
    ":Vehiculo" -> ":MovimientoComun": mover (unaCalle, :Vehiculo)
    ":MovimientoComun" -> ":CalleComun": serTransitada (:Vehiculo)
     Activate ":CalleComun"
    ":CalleComun" -> ":SorpresaFavorable": serEncontradaPor (:Vehiculo)
    Activate ":SorpresaFavorable"
    ":SorpresaFavorable" -> ":Vehiculo": disminuirCantidadMovimientosEnPorcentaje (porcentaje)
     Deactivate ":SorpresaFavorable"
    ":MovimientoComun" <-- ":CalleComun": nuevaPosicion:Posicion
    Deactivate ":CalleComun"
    ":Vehiculo" <-- ":MovimientoComun": nuevaPosicion:Posicion
    Deactivate ":MovimientoComun"



@enduml