@startuml
'https://plantuml.com/sequence-diagram
title Diagrama Auto Atraviesa La Ciudad Y Se Encuentra con Pozo Penalizada En Tres Movimientos
autonumber
actor ":TestCase"

Activate ":TestCase"
   ":TestCase" -> "unVe:Vehiculo": moverseHacia (unaDireccion)
    Activate "unVe:Vehiculo"
    create ":MovimientoComun"
    "unVe:Vehiculo" -> ":MovimientoComun": <<new Movimiento (unaDireccion) >>
    "unVe:Vehiculo" -> ":MovimientoComun": moverse (unVe)
    Activate ":MovimientoComun"
    ":MovimientoComun" -> "unVe:Vehiculo": cambiarPosicionHacia (:PosicionRelativa)
    ":MovimientoComun" -> ":Grilla": aplicarElementoUbicable(unVe)
    Deactivate ":MovimientoComun"
    Activate ":Grilla"
    loop Por Cada Ubicable de la Lista
    ":Grilla" -> "unVe:Vehiculo": toparseCon(:Ubicable)
    "unVe:Vehiculo" -> ":Ubicable": estaEnPosicion(:Posicion)
    Activate ":Ubicable"
    end


    "unVe:Vehiculo" <- ":Ubicable": aplicarPenalizacion(Pozo)
    "unVe:Vehiculo" -> ":Auto": aplicarPenalizacion(Pozo)
    Activate ":Auto"
    return cantidadDeMovimientos
    Deactivate ":Ubicable"
    Deactivate ":Grilla"
    ":TestCase" -> "unVe:Vehiculo": getCantidadMovimientos()
    return cantidadDeMovimientos

@enduml